retailer: Tamimi

essential_columns:
  - Store
  - Store ID
  - Product
  - Product ID
  - Brand
  - H1:Category
  - Selling_Unit
  - Sales Exc Tax
  - Units
  - Volume

rename_map:
  Store: "Store Description"
  Product ID: "SKU"
  Product: "SKU Description"
  Selling_Unit: "Sales Unit"
  Sales Exc Tax: "Sales_Amount"
  Sales Qty: "Sales_Quantity"